# Generated by Django 2.2.6 on 2019-12-06 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('instaName', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(max_length=200)),
                ('googleID', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='favoriteMusician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image1', to='user.musician')),
                ('image2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image2', to='user.musician')),
                ('image3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image3', to='user.musician')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
    ]
